#!/bin/sh
echo "Clean"
echo "suppression des fichiers *~ .java.bak *.class"
find . -name '*~' -type f -exec rm -f {} \;
find . -name '*.bak' -type f -exec rm -f {} \;
find . -name '*.class' -type f -exec rm -f {} \;
echo "suppression de la javadoc"
rm -rf ./docs/javadoc/*
echo "Clean End"